export {default  as logo} from "./BCBCPL_LOGO.png"
export {default  as Banner1} from "./Puri-Railway-Station.jpg"
export {default  as Banner2} from "./Fish Market, Basta.jpg"
export {default  as Banner3} from "./OPTCL-Quater-Complex.jpg"
export {default  as Banner4} from "./Aluminium-Park.jpg"
export {default  as Banner5} from "./DHH, Bhadrak.jpg"
export {default  as Banner6} from "./EMC Park.jpg"
export {default  as Banner7} from "./HMVTI.jpg"
export {default  as About} from "./about.jpeg"
export {default  as Testi} from "./testi.png"
export {default  as Member1} from "./member1.jpeg"
export {default  as Member2} from "./member2.webp"
export {default  as Member3} from "./member3.jpeg"
export {default  as MoreAbout} from "./moreAbout.jpg"
export {default  as Con1} from "./c1.png"
export {default  as Con2} from "./c2.png"
export {default  as Con3} from "./c3.png"
export {default  as Ser1} from "./s1.png"
export {default  as Ser2} from "./s2.png"
export {default  as Ser3} from "./s3.png"
export {default  as Ser4} from "./s4.png"
export {default  as Ong1} from "./on1.webp"
export {default  as Ong2} from "./on2.webp"
export {default  as Ong3} from "./on3.webp"
export {default  as Ong4} from "./on4.webp"
export {default  as Ong5} from "./on5.webp"
export {default  as Ong6} from "./on6.webp"
export {default  as Ong7} from "./on7.webp"
export {default  as Ong8} from "./on8.webp"
export {default  as Comp1} from "./cp1.webp"
export {default  as Comp2} from "./cp2.webp"
export {default  as Comp3} from "./cp3.webp"
export {default  as Comp4} from "./cp4.webp"
export {default  as Comp5} from "./cp5.webp"
export {default  as Comp6} from "./cp6.webp"
export {default  as Comp7} from "./cp7.webp"
export {default  as Comp8} from "./cp8.webp"
export {default  as Comp9} from "./cp9.webp"
export {default  as Comp10} from "./cp10.webp"
export {default  as Comp11} from "./cp11.webp"
export {default  as Founder} from "./founder.webp"
export {default  as Eqp1} from "./eq1.webp"
export {default  as Eqp2} from "./eq2.webp"
export {default  as Eqp3} from "./eq3.webp"
export {default  as Gallery1} from "./Conference Internal Meeting.jpg"
export {default  as Gallery2} from "./Office Enterance.jpg"
export {default  as Gallery3} from "./Office Internal Discussion with Sr. GM.jpg"
export {default  as Gallery4} from "./Office Lobby.jpg"
export {default  as Gallery5} from "./Office Reception Area.jpg"
export {default  as Gallery6} from "./Office Team Photo.jpg"
export {default  as Gallery7} from "./Office Workstation.jpg"
export {default  as Cer1} from "./iso 9001.png"
export {default  as Cer2} from "./udyam.png"
export {default  as Cer3} from "./iso 14001.png"
